[package]
name = "block-dag"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
chrono = "0.4.38"
chrono-tz = "0.9.0"
hex = "0.4.3"
json = "0.12.4"
